model:
  name: gemnet_oc
  num_spherical: 7
  num_radial: 128
  num_blocks: 4
  emb_size_atom: 256
  emb_size_edge: 512
  emb_size_trip_in: 64
  emb_size_trip_out: 64
  emb_size_quad_in: 32
  emb_size_quad_out: 32
  emb_size_aint_in: 64
  emb_size_aint_out: 64
  emb_size_rbf: 16
  emb_size_cbf: 16
  emb_size_sbf: 32
  num_before_skip: 2
  num_after_skip: 2
  cutoff: 12.0
  max_neighbors: 30
  extensive: false          # IS2RE = total energy
  activation: silu

optim:
  batch_size: 4             # Colab-safe
  eval_batch_size: 4
  lr_initial: 5.e-4
  optimizer: AdamW
  scheduler: ReduceLROnPlateau
  max_epochs: 30
  loss_energy: mae
  energy_coefficient: 1
