# ----- model hyper-params (flattened) -----
name: gemnet_oc
num_spherical: 7
num_radial: 128
num_blocks: 4
emb_size_atom: 256
emb_size_edge: 512
emb_size_trip_in: 64
emb_size_trip_out: 64
emb_size_quad_in: 32
emb_size_quad_out: 32
cutoff: 12.0
max_neighbors: 30
extensive: false
activation: silu

# ----- optim hyper-params -----
batch_size: 4
eval_batch_size: 4
learning_rate: 5.e-4        #
max_epochs: 30
loss_energy: mae
